package com.laptrinhdidong.nhom3.btvntuan1

import androidx.lifecycle.MutableLiveData

object DataStore {
    private var list: MutableList<Account> = mutableListOf()
    ///hàn lấy ra tất cả account (dùng để so sánh ở trang login)
    fun getListAccount():MutableList<Account>
    {
        return list
    }
    ///hàm thêm mới account (dùng ở trang signup)
    fun addAccount(account: Account)
    {
        list.add(account)
    }
    ///các hàm set (dùng ở trang profile)
    fun setFullNameAccount(index: Int?,fullname : String)
    {
        list[index!!].fullname=fullname
    }
    fun setEmailAccount(index: Int?,email: String)
    {
        list[index!!].email=email
    }
    fun setPhoneAccount(index: Int?,phone: String)
    {
        list[index!!].phone = phone
    }
    fun getDataSet(): List<Restaurant>{
        return listOf(
                Restaurant("33760", "Du Miên Garden Cafe - Phan Văn Trị", "7 Phan Văn Trị, P. 10", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("978", "Country House Cafe", "18C Phan Văn Trị, P. 10", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("82801", "Hẻm Spaghetti - Nguyễn Oanh", "212/22 Nguyễn Oanh, P. 17", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("149154", "Lava Coffee - Quang Trung", "61 Quang Trung, P. 10", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("194867", "Mì Cay Naga - 224 Phạm Văn Đồng", "224 Phạm Văn Đồng, P.1 ", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("25656", "City House Cafe - Sân Vườn Lãng Mạn", "21 Huỳnh Khương An, P. 5", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("66844", "Nhi Nhi Quán - Đặc Sản Phan Rang", "125/48 Lê Đức Thọ, P. 17", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("33645", "Yuri Yuri - Ẩm Thực Hàn Quốc", "358 Nguyễn Văn Nghi, P. 7", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("252442", "Trà Sữa Gong Cha - 貢茶 - Phan Văn Trị", "595 Phan Văn Trị, P. 5", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("12513", "Oasis Cafe", "26/14 Phạm Văn Đồng, P. 3", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("199622", "Buzza Pizza - Emart Gò Vấp", "Tầng Trệt Emart Gò Vấp - 366 Phan Văn Trị, P. 5", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("651063", "Dallas Cakes & Coffee - Quang Trung", "6 Quang Trung, P. 10", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("60915", "Hot & Cold - Trà Sữa & Xiên Que - Quang Trung", "804 Quang Trung", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("112585", "Papaxốt - Quang Trung", "458 Quang Trung", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("91979", "SaiGon Chic Cafe", "82 Đường Số 27, P. 6", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("28883", "Pizza Hut - Quang Trung", "283 Quang Trung", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("129725", "Bánh Mì Chảo & Món Ngon Hoa Việt - Quán Cô 3 Hậu", "36 Đường Số 18, P. 8", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("46668", "Kichi Kichi Lẩu Băng Chuyền - Quang Trung", "1 Quang Trung", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("158187", "The Coffee House - Quang Trung", "293 Quang Trung", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("30102", "Cánh Đồng Quán - Lẩu Nướng Tại Bàn - Dương Quảng Hàm", "310/14 Dương Quảng Hàm, P. 5", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("83857", "Chú Tèo Buffet Nướng 99K - K26 Dương Quảng Hàm", "N01 Chung Cư K26 Dương Quảng Hàm, P. 7", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("212102", "Food Court - E Mart Gò Vấp", "Tầng Trệt E - Mart Gò Vấp, 168 Phan Văn Trị, P. 5", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("67764", "Bánh Tráng Deli & Xiên Que - Lê Đức Thọ", "730/7/5 Lê Đức Thọ, P. 15", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("232015", "Cowboy Jack's - American Dining - Lotte Mart Gò Vấp", "Tầng 1, Lotte Mart Gò Vấp, 242 Nguyễn Văn Lượng, P. 10", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("674432", "Food House - Nguyễn Kiệm", "800 Nguyễn Kiệm", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("106797", "Domino's Pizza - Quang Trung", "582 Quang Trung , P. 10", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("147114", "Hana BBQ & Hot Pot Buffet - Phan Văn Trị", "705 - 707 Phan Văn Trị, P. 7", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("231730", "Lẩu Cua Đất Mũi - Quang Trung", "769 Quang Trung, P. 12", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("135862", "Trà Sữa Hiberry - Nguyễn Văn Bảo", "7 Nguyễn Văn Bảo, P. 4", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("78167", "Trà Sữa Bobapop - Quang Trung", "343 Quang Trung, P. 10", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("5023", "I Love Kem - Thống Nhất", "257 Thống Nhất, P. 11", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("236020", "OH-LA DELI - Quán Ăn Hàn Quốc", "72/14A Đường Số 30, P. 6", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("166732", "Texas Chicken - Quang Trung", "578 Quang Trung, P.11", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("43019", "Sumo BBQ - Quang Trung - Buffet Nướng & Lẩu", "50 Quang Trung, P. 10", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("4146", "Gà Rán KFC - BigC Gò Vấp", "792 Nguyễn Kiệm, P. 3", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("165239", "King BBQ Buffet Vincom Quang Trung", "B1-11 Vincom Quang Trung, 190 Quang Trung", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("197985", "Gogi House - Thịt Nướng Hàn Quốc - E-Mart Gò Vấp", "Tầng 1 E Mart Gò Vấp, 168 Phan Văn Trị, P. 5", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("8266", "Nhà Hàng Những Người Bạn", "14 Phan Văn Trị, P. 7", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("289632", "Bún Mắm Hai Lúa", "401 Cây Trâm", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("245681", "Gà Nướng Ò Ó O - Quang Trung", "50/25 Quang Trung, P. 10", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("114471", "Kem Baskin Robbins - Quang Trung", "82 Quang Trung, P. 10", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("3629", "Xôi Chè Bùi Thị Xuân - Nguyễn Oanh", "144 Nguyễn Oanh, P. 17", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("201198", "Starbucks Coffee - Emart", "Emart, 366 Phan Văn Trị, P. 5", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("73213", "Thanh Thúy - Ẩm Thực Miền Trung", "679 Quang Trung, P.11", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("628238", "Nem Nướng & Bún Thịt Nướng Mr. Nem - Cây Trâm", "400 Cây Trâm. P. 8", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("673904", "Đông Mập - Trà Sữa & Gà Cay Phô Mai", "164/5 Nguyễn Oanh, P. 17", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("70256", "Bánh Mì Cóc - Bánh Mì Gà Xé - 112A Nguyễn Thái Sơn", "112A Nguyễn Thái Sơn, P. 3", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("209038", "Sweet Sushi - Sushi & More", "61 Nguyễn Văn Nghi, P. 4", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("145745", "Chip Chip - Trà Sữa Thạch Phô Mai - Lê Đức Thọ", "40/20 Lê Đức Thọ, P. 7", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("256733", "Thức Coffee - Nguyễn Thái Sơn", "320 Nguyễn Thái Sơn", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("69227", "Hồng Diên - Bánh Căn & Bánh Xèo", "269 Nguyễn Văn Lượng, P. 10", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("128303", "Trà Sữa Milk Tea Land - Lê Đức Thọ", "650 Lê Đức Thọ, P. 15", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("766016", "Làng Vòng - Bún Đậu Mắm Tôm & Bún Chả", "413 Phan Huy Ích, P. 14", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("147845", "Trà Sữa Tiên Hưởng - Phan Văn Trị", "551 Phan Văn Trị, P. 5", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("10547", "Quán Bò Hai Châu - Cây Trâm", "268 Cây Trâm, P. 9", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("124798", "Cút Vịt Lộn 10 Món", "775 Phan Văn Trị, P. 7", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("753428", "TL Sushi", "34 Đường Số 45, P. 14", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("120212", "McDonald's - Quang Trung", "1 Quang Trung, P. 3", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("21131", "Ốc Chánh", " 55/7 Nguyễn Văn Công, P. 3", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("125133", "Phá Lấu Cô Ba Vân", "288 Thống Nhất, P. 10", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("35772", "Lotteria - Quang Trung", "9 Quang Trung, P. 11", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("112595", "Food Court - AEON Citimart Quang Trung", "672 Quang Trung", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("49791", "Chất BBQ - Xiên Nướng Đồng Giá", "192/2 Nguyễn Oanh", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("166259", "Sườn Cây Nướng & Beer - Quang Trung", "474 Quang Trung, P. 10", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("139759", "Trà Sữa Tiên Hưởng - Quang Trung", "69 Quang Trung, P. 10", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("732364", "Busan Korean Food - Phan Văn Trị", "763 - 765 Phan Văn Trị, P. 7", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("9238", "Địa Đàng Cafe ", "389 Cây Trâm,  P. 8", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("769154", "Koi Sushi", "549 Phan Văn Trị, P. 5", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("87381", "Quán Nướng Ngói Sài Gòn", "232 Phạm Văn Đồng, P. 1", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("4861", "Bò Né Hai Chị Em - Quang Trung", "460 Quang Trung, P. 10", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("146525", "Pizza Đà Lạt - Lê Lợi", "13 Lê Lợi", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("200593", "Bún Đậu Hoàng Anh", "40/78 Lê Thị Hồng, P. 17", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("165175", "Tasaki BBQ Vincom Quang Trung", "Tầng B1, Vincom Quang Trung, 190 Quang Trung, P. 10", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("103121", "Phố Nướng Anh Em - Dương Quảng Hàm", "258 Dương Quảng Hàm", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("83883", "Trà Sữa Tam Cốc", "543A/3 Lê Đức Thọ, P.17", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("91344", "Lâm Bô Hotpot & Barbecue - Quang Trung", "1 Quang Trung, P. 3", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("209045", "Gyu-Kaku Japanese BBQ - Vincom Plaza Gò Vấp", "Tầng 4, Vincom Plaza Gò Vấp, 12 Phan Văn Trị, P. 7", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("292105", "Bún Cay Thái 2 Thuận - Nguyễn Văn Khối (Cây Trâm),", "320 Nguyễn Văn Khối (Cây Trâm),, P. 9", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("44618", "ABC Bakery - Quang Trung", "34 - 36 Quang Trung, P. 10", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("777657", "Chattea - Trà Chất - Phan Văn Trị", "624 Phan Văn Trị, P. 7", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("3692", "Bún Bò Sông Hương - Quang Trung", "740 Quang Trung, P. 8", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("3711", "Mộc Miên Cafe ", "830 Quang Trung, P. 8", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("10531", "Lẩu Ếch Sáu Hiếu", "429/9 Quang Trung, P. 10", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("165167", "Daruma - Quán Ăn Nhật Bản - Vincom Quang Trung", "Tầng B1 Vincom Quang Trung, 190 Quang Trung, P. 10", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("79097", "Steak Bin & Pizza - Đường Số 8", "85 Đường Số 8, P. 11", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("159575", "MNS ICE SNOW - Đá Bào Mật Trái Cây Rừng - Quang Trung", "69D Quang Trung, P. 8", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("8494", "Quán Ăn Hàn Quốc - Quang Trung", "445 Quang Trung, P.10", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("242782", "Metropolis Coffee", "1230 Quang Trung, P. 8", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("244259", "Bún Thịt Nướng Kiều Bảo 2", "850 Quang Trung, P. 8", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("14923", "Ốc Vui Vẻ", "153/48/38 Lê Văn Thọ, P. 8", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("233233", "Lavida Coffee And Tea - Quang Trung", "661 Quang Trung", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("127789", "Xiên Nướng KingKong", "19 Phạm Ngũ Lão, P. 3", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("152670", "Megustas Coffee & More", "301 Thống Nhất, P. 11", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("25677", "Trà Sữa & Thức Ăn Nhanh Tombo - Thống Nhất", "447 Thống Nhất", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("206130", "NewDays Japanese Matcha Cafe - Vincom Plaza Gò Vấp", "Tầng 4, Vincom Plaza Gò Vấp, 12 Phan Văn Trị, P. 7", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("195094", "Sushi Đường Phố - Sake Kissho - Lê Văn Thọ", "368 Lê Văn Thọ, P. 11", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("259142", "Chè Thái Ý Phương - Quang Trung", "663 Quang Trung", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("228809", "Bánh Bông Lan Trứng Muối Sunny Bakery - Shop Online", "1244/40/2B Lê Đức Thọ, P. 13", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("17010", "Bún Mắm Cô Ba - Phan Huy Ích", "451 Phan Huy Ích, P. 14 ", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("211125", "Hotpot Story - Vincom Plaza Gò Vấp", "L4 - 07, Vincom Plaza Gò Vấp, 12 Phan Văn Trị, P. 7", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("107543", "Dunkin' Donuts - Quang Trung", "Tầng Trệt, 304A Quang Trung, P. 11", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("739277", "The Alley - Trà Sữa Đài Loan - Quang Trung", "56 Quang Trung, P. 10", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("731577", "Toocha - Trà Sữa Không Mập - Phan Văn Trị", "366A23 Phan Văn Trị", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("273430", "Lẩu Gà Ớt Hiểm 109 - Phạm Ngũ Lão", "19 Phạm Ngũ Lão, P. 3", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("98714", "Bò Cười Quán", "39 Lê Đức Thọ", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("710953", "Đen Đá Cafe - Trà Sữa & Trà Đào - Phan Văn Trị", "366 Phan Văn Trị", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("736453", "Con Gà Mái - Cơm Gà Phú Yên - Quang Trung", "181 Quang Trung, P. 10", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("718524", "Trà Sữa Heekcaa Việt Nam - Phan Văn Trị", "15K (Hẻm 424), Phan Văn Trị, P. 7", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("28874", "Beefsteak Hoàng Gia Quý Tộc", "77 - 79 Đường Số 11", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("95695", "Ăn Vặt Kem Gà - Giao Hàng Tận Nơi", "80/5 Nguyễn Văn Công, P. 3", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("40839", "Món Huế O Hiệp - Shop Online", "44/9 Đường Số 45", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("4592", "The Adora - Tiệc Cưới Hội Nghị - Nguyễn Kiệm", "371 Nguyễn Kiệm, P. 3", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("23005", "Phá Lấu Bò - Cây Trâm", "208 Cây Trâm", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("103426", "Bánh Flan & Bánh Bèo - Chợ Hạnh Thông Tây", "Chợ Hạnh Thông Tây", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("77277", "Bánh Flan Tây Ban Nha", "119 Đường Số 1, P. 11", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("733764", "Koi Thé Café - Phan Văn Trị", "L6.2 Khu Dân Cư City Land, Phan Văn Trị, P. 5", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("688453", "Royaltea Việt Nam - Trà Sữa Hồng Kông - Phan Văn Trị", "366A18 Phan Văn Trị, P. 5", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("102741", "Lộ Thiên Quán - Nguyễn Oanh", "222 Nguyễn Oanh, P. 17", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("683740", "Family Garden Cafe", "438 Phan Văn Trị, P. 7", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("649168", "Bách Restaurant - Ẩm Thực Trung Hoa", "481 Phan Văn Trị, P. 5", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("286930", "The Hideout Coffee & Desserts", "190 Lê Văn Thọ, P. 11", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("704599", "Royaltea Việt Nam - 108 Quang Trung", "108 Quang Trung, P. 10", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("31538", "Lẩu Đồng Quê 3 - Đường 13", "57/2 Đường 13, P. 11", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("713996", "TocoToco Bubble Tea - Phan Văn Trị", "449 Phan Văn Trị, P. 5", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("235771", "Highlands Coffee - Lotte Gò Vấp", "Lotte Mart Gò Vấp, 242 Nguyễn Văn Lượng", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("126289", "Cremista - Kem Cuộn Thái Lan", "621 Lê Đức Thọ,P. 16", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("100543", "Bánh Bèo Chén", "107/39 Đường Số 11, P. 11", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("890440", "Ù Quay - Chân Gà Sả Tắc - Lê Thị Hồng - Shop Online", "28/25 Lê Thị Hồng, P. 17", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("255841", "Cháo Sườn Cô Giang - Nguyễn Oanh", "164 Nguyễn Oanh, P. 17", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("128039", "Jollibee - Coopmart Quang Trung", "Tầng 2, Coopmart Quang Trung, 304A Quang Trung, P. 11", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("658947", "The Pizza Company - Quang Trung Gò Vấp", "638 Quang Trung, P. 11", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("644658", "Food In Box - Fastfood", "285B Phạm Văn Chiêu, P. 14", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("10685", "Pizza Inn - Quang Trung", "229 Quang Trung, P. 10", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("629960", "Effoc Cafe - Quang Trung", "777 Quang Trung, P. 8", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("73933", "Sushi Street - Sushi Đường Phố", "913 Phan Văn Trị, P. 7", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("652500", "Sky Heaven Coffee", "41/29 Nguyễn Oanh", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("631756", "Ajikoi - Ice Cream & Matcha - Phạm Văn Đồng", "286 Phạm Văn Đồng, P. 1", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("73628", "Xiên Nướng Pé Mập", "256/6 Dương Quảng Hàm, P. 5", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("232280", "Susalan - Coffee & Food House", "590/2 Phan Văn Trị, P. 7", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("69359", "Bánh Tráng Nướng Gà Xé", "2E Lê Lợi, P. 4", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("130206", "Kem Xôi Dừa - Nguyễn Văn Nghi", "290 Nguyễn Văn Nghi, P. 7", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("130164", "Bảo Lộc - Nướng Ngói - Phạm Văn Đồng", "160 Phạm Văn Đồng ", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("663059", "Naga - Mì Gà Quay Da Giòn", "C22 Phan Văn Trị", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("124745", "Han Flan - Trà Sữa & Chè Khúc Bạch - Lê Văn Thọ", "336 Lê Văn Thọ, P. 11", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("314815", "Gà Rán Popeyes - Lê Đức Thọ", "121 Lê Đức Thọ", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("20143", "Súp Cua Hạnh - Nguyễn Thái Sơn", "12 Nguyễn Thái Sơn, P. 3", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("2372", "2 Tòn Quán - Món Ngon Phan Rang", "570 Lê Quang Định, P. 1", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("144524", "Bánh Cuốn Tây Sơn - Phạm Văn Đồng", "132 Phạm Văn Đồng, P. 3", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("703949", "Bún Bò Huế Xưa - Phạm Văn Đồng", "309 Phạm Văn Đồng, P. 1", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("708034", "Tân Hải Vân - Ẩm Thực Trung Hoa - Phan Văn Trị", "503 Phan Văn Trị", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("104821", "Racing Beer Club - RBC", "1 Quang Trung", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("316270", "SaSin - Mì Cay 7 Cấp Độ Hàn Quốc - Lê Văn Thọ", "351 Lê Văn Thọ, P. 9", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("658101", "Gành Ốc Quán", "68 Đường Số 1, P. 16", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("739290", "Bánh Bột Lọc Cô Bê", "327/28/9 Quang Trung, P. 10", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("82871", "Ốc Hoàng - Lê Thị Hồng", "40/40 Lê Thị Hồng", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("29344", "Bánh Canh Cá Lóc Cường Đô La - Lê Thị Hồng", "Đối Diện 42 Lê Thị Hồng, P. 17", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("769777", "Royaltea Center Hills - Gò Vấp", "71 Đường Số 7, KDC Cityland Center Hills, P. 7", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("299285", "Mẹt - Bún Đậu Mắm Tôm - Phan Văn Trị", "825 Phan Văn Trị", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("707241", "Ngon 24h - Ăn Vặt Miền Quê", "19 Phạm Văn Đồng", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("656152", "Uncle Tea - Trà Đài Loan - Lê Lợi", "60 Lê Lợi, P. 4", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("125075", "Bột Chiên A Bình - Đường Số 18", "28 Đường Số 18, P. 8", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("68497", "Bún Thịt Nướng Ca Na", "656/17 Quang Trung, P. 11", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("649966", "Gà Nướng Lu Việt Hương - Phạm Văn Đồng", "20 Phạm Văn Đồng, P. 3", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("753717", "Dì Ba - Nem Nướng Nha Trang", "354/3 Nguyễn Thái Sơn, P. 5", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("138289", "Kem Cuộn Mập Mập - Phạm Văn Đồng", "343 Phạm Văn Đồng, P. 1", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("202110", "Sentosa Food - Cháo Ếch Singapore - Quang Trung", "648 Quang Trung, P. 11", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("210811", "Beefsteak Hai Con Bò - Quang Trung", "417 Quang Trung", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("698823", "Royaltea Vietnam - Lotte Mart Gò Vấp", "Tầng Trệt Lotte Mart Gò Vấp, 242 Nguyễn Văn Lượng, P. 10", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("160920", "Uyên Phương - Bánh Canh & Chả Cuốn", "24 Lê Đức Thọ, P. 7", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("287030", "Mì Cay Ớt Ma - Lê Văn Thọ", "4 Lê Văn Thọ. P. 11", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("292136", "Mẹt Quán - Ẩm Thực Tây Bắc", "1117 Phan Văn Trị, P. 10", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("691981", "SNOB Coffee - Phan Văn Trị", "527 Phan Văn Trị", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("96348", "Bánh Khọt Vũng Tàu", "62 Đường Số 8, P. 11", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("23579", "Ốc Bống - Nguyễn Kiệm", "101/717C Nguyễn Kiệm", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("760594", "Dinosaur Hotpot & Sushi", "543/13 Lê Đức Thọ, P. 7", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("773195", "Three O'clock - Coffee & Tea - Phan Văn Trị", "459 - 461 Phan Văn Trị, P. 5", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("81428", "Hủ Tíu Mì 217", "217 Nguyễn Văn Nghi, P. 7 ", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("85647", "Xiên Nướng 5K", "70Bis Nguyễn Văn Lượng, P. 10", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("86008", "Steak Viet - Phan Văn Trị", "610 Phan Văn Trị, P. 7", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("232712", "Hana - Mì Cay 7 Cấp Độ Hàn Quốc - Quang Trung", "751 Quang Trung, P. 12", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("4239", "Sài Gòn Givral Bakery - 513 Quang Trung", "513 Quang Trung, P. 10", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("774377", "Phúc Long Coffee & Tea - Vincom Quang Trung", "190 Quang Trung, P. 10", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("740250", "Thế Giới Steak - Phan Văn Trị", "493 Phan Văn Trị, P. 5", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("699146", "Taste Tea - Nguyễn Oanh", "89 Nguyễn Oanh", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("66896", "Mì Vịt Tiềm A Cón - Quang Trung", "557 Quang Trung, P. 10", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("660382", "Trà Sữa Huy's - Quang Trung", "781 Quang Trung, P. 12", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("76906", "Bánh Xèo Bình Định - 244 Lê Đức Thọ", "244 Lê Đức Thọ, P. 6", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("24925", "Bánh Canh Ghẹ Bảy Liên", "778F Nguyễn Kiệm, P. 4", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("2849", "Brodard Bakery - Quang Trung ", "08 Quang Trung, P. 10", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("112575", "Tài Vượng Quán 2 - Lẩu & Nướng - Phạm Văn Đồng", "35 Phạm Văn Đồng, P. 3", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("165237", "Cơm Nướng Hotto - Vincom Quang Trung", "Tầng B1 Vincom Quang Trung, 190 Quang Trung, P. 10", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("313089", "Mizu - Trà Kiểu Nhật", "33 Nguyễn Văn Bảo, P. 4", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("25208", "Mì Quảng Chính Hiệu", "163 Lê Văn Thọ, P. 8", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("638672", "Youth House Coffee - Nguyễn Văn Nghi", "29 Nguyễn Văn Nghi, P. 4", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("159153", "Trà Sữa Bubble Fly - 23 Lê Lợi", "23 Lê Lợi, P. 4", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("710828", "Moda House Coffee", "11 Nguyễn Oanh, P. 10", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("242389", "Mì Cay Hara", "11 Nguyễn Văn Nghi, P. 4", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("212471", "Hủ Tiếu Mực Ông Già Cali - Phạm Văn Đồng", "288 Phạm Văn Đồng, P. 1", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("190586", "Obi Cafe", "5 Nguyễn Duy Cung, P. 12", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("796994", "Hà Đô - Bún Thái Hải Sản - Shop Online", "42 Lê Thị Hồng, P. 17", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("775540", "Chuti Korean Food - Phan Văn Trị", "477 Phan Văn Trị", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("171029", "Pizza Pan", "446 Cây Trâm, P. 9", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("108610", "Bụi Sài Gòn Nhà Hàng & Cafe", "792 Nguyễn Kiệm, P. 3 ", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("222491", "Mì Nhật Tano Q", "77 - 79 Đường Số 11, P. 11", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("44574", "Lẩu Dê Đức Dưỡng", "607/2/8 Tân Sơn, P. 12", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("781782", "Ghiền Sữa Chua Nếp Cẩm 39", "1351/1/2 Phan Văn Trị, P. 10", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("190751", "Food House Restaurant", "18B Phan Văn Trị, P. 10", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("721062", "Hutong - Hotpot Paradise - Quang Trung", "1 Quang Trung", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("1024", "Tuệ Mẫn Cafe - Êm Đềm Một Không Gian", "452 Cây Trâm, P.9", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("3691", "Thủy Mộc Cafe - Lê Lợi", "94 Lê Lợi, P. 4", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("240633", "Cô Túc - Bánh Canh & Mì - Lê Đức Thọ", "115/47 Lê Đức Thọ, P. 17", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("259843", "Canh Bún Thái Sơn", "269 Nguyễn Thái Sơn, P. 7", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("228210", "Quán Chay Thiên Kim ", "359 Cây Trâm, P. 8", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("91201", "Trà Sữa Hoa Hướng Dương - Nguyễn Văn Nghi", "318 Nguyễn Văn Nghi, P. 4", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("633665", "Hàu Né 3 Ngon - Hàu Né & Bò Bít Tết", "414 Thống Nhất, P. 16", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("72067", "Bánh Bèo 53", "53 Nguyễn Thái Sơn, P. 4 ", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("123349", "Mây Thai Tea - Ăn Vặt Thái", "1074 Quang Trung, P. 8", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("242876", "Phá Lấu & Súp Ngũ Sắc", "535/8 Thống Nhất, P. 16", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("70776", "Cơm Tấm Bụi Sài Gòn - Gò Vấp", "4 Đường Số 7, KDC Cityland, P. 7", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("713718", "Hẹ Quán - Ăn Vặt Phú Yên", "68 Phạm Văn Đồng, P. 3", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("702084", "Alas - Pets & Garden Coffee", "50/8 Quang Trung, P. 10", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("148111", "Bún Đậu Hà Nội - Thống Nhất", "284 - 286 Thống Nhất. P. 10", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("786623", "Ajikoi By Tea, Coffee & Cream - Phan Văn Trị", "507 Phan Văn Trị, P. 5", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("681773", "Buffet Haha", "292 Nguyễn Văn Lượng, P. 17", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("292957", "I.Korea.U - Ẩm Thực Hàn Quốc", "808 Quang Trung, P. 8", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("161512", "Papiyon Coffee - Nguyễn Văn Lượng", "46 Nguyễn Văn Lượng, P. 17", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("745008", "Gà Chảnh - Gà Nướng Tóp Mỡ - Shop Online", "214/50/6 Nguyễn Oanh, P. 17", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("650843", "Nhà Hàng Những Chàng Trai - Buffet BBQ Không Khói", "233 Phan Huy Ích, P. 14", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("746877", "Bean Plus Coffee & Tea", "465/7 Phan Văn Trị, P. 5", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("891423", "Rau Má Pha - Phan Văn Trị", "507 Phan Văn Trị", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("218822", "Super Prime Pizza - E Mart Gò Vấp", "Tầng 1 E - Mart Gò Vấp, 366 Phan Văn Trị, P. 5", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("30737", "Món Ngon Quy Nhơn", "194 Nguyễn Thái Sơn (Số Cũ 142 Nguyễn Thái Sơn),", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("644029", "Bánh Su Kem Chewy Junior - Coopmart Quang Trung", "GF-09B, Tầng Trệt Coopmart Quang Trung, 304A Quang Trung, P. 11", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("131869", "Bún Đậu Xóm Mới - Lê Đức Thọ", "1022 Lê Đức Thọ", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("743484", "FOX Tea - Trà Sữa & Ăn Vặt", "202 Đường Số 8, P. 11", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("122310", "Mai Hoa - Bò Lá Lốt, Mỡ Chài ", "570 Lê Đức Thọ, P. 17 ", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("699352", "Tokyo Deli - Phan Văn Trị", "366A3 Phan Văn Trị, P. 5", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("109822", "Ngộ - Lẩu & Nướng Hải Sản", "69 Phạm Văn Chiêu, P. 14", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("705229", "Cơm Tấm Cali 20 - Phạm Ngũ Lão", "278 Phạm Ngũ Lão", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("121843", "Thành Danh - Bánh Tráng Trộn Tây Ninh", "245 Lê Văn Thọ, P. 11", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("207545", "Quán Tư Mập - Cá Lóc Nướng", "33 Đường Số 8, P. 11", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("232296", "Food Court - Lotte Mart Gò Vấp", "242 Nguyễn Văn Lượng, P. 10", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("664391", "Minh Anh - Quán Mì Cay & Bánh Mì Chảo", "440/60 Thống Nhất, P. 16", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("769066", "Kem Xôi Dừa Bu Bu - Phan Văn Trị", "622 Phan Văn Trị, P. 7", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("893821", "Chè Thanh Xuân - Chè Tuyết Yến Nhựa Đào", "28/25 Lê Thị Hồng, P. 17", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("629788", "JNGON - Cơm Gà Chiên Giòn", "54 Đường Số 4, P. 7", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("1357", "Lẩu Dê SOS Làng Hoa", "12/6A Đường 10, P. 9", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("714938", "Sương Sáo Đài Loan", "2 Đường Số 2, KDC Cityland, P. 7", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("669899", "Hali Sushi - Nguyễn Văn Lượng", "227 Nguyễn Văn Lượng, P. 10", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("236293", "Bếp Ông Bà Tư - Quán Ăn Hàn Nhật", "127/32 Nguyễn Tư Giản, P. 12", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("10511", "Ốc Hoàng - Trương Minh Giảng", "11 Trương Minh Giảng, P. 17", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("107629", "Rin-O Tea - Trà Sữa & Trái Cây Tô", "40/36 Lê Thị Hồng, Khu Phố 12, P. 17", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("677028", "Bò Bía 98 - Shop Online", "98 Nguyễn Thượng Hiền, P. 1", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("213883", "Sữa Chua Tin Tin - Shop Online", "2 Đường Số 20, Dương Quảng Hàm", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("71105", "Quán Phương - Bún Bắp Bò", "2 Nguyễn Oanh, P. 7", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("247811", "Xoài Lắc Lão Xoài", "60 Phạm Văn Chiêu, P. 8", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("727088", "Ăn Vặt Cô Thơ - Shop Online", "15/29bis Nguyễn Du", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("165240", "BreadTalk - Vincom Quang Trung", "L1-11 Vincom Quang Trung", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("4484", "Phố Nướng Tư Trì - Lê Văn Thọ", "499 Lê Văn Thọ, P. 9", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("156929", "Velvet Garden - Bùi Quang Là", "114 Bùi Quang Là, P. 12", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("142098", "MỘC - Ẩm Thực Than Hồng", "1B Lê Đức Thọ, P. 7", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("795931", "Bò Lế Rồ - Bò Nhúng Sốt & Nhúng Lẩu - Phan Văn Trị", "1445 Phan Văn Trị, P. 10", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("49571", "Bánh Bao Thơm Ngon - Lê Lợi", "58 Lê Lợi, P. 4", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("188302", "Bánh Đúc Nóng Hương Quê", "258 Lê Văn Thọ, P. 11", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("2414", "Khoảng Lặng Coffee", "E10C An Nhơn, P. 17", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("82999", "Miss Kim - Mực Sạch Rim", "566/137/6 Dương Quảng Hàm, P. 5", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("209046", "Trà Sữa Lee Cường", "115/53 Lê Đức Thọ, P. 17", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("95070", "Bò Tơ Tây Ninh Năm Sánh - Nguyễn Oanh", "152 Nguyễn Oanh, P. 17", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("258640", "Sữa Việt - Trà Sữa Nhà Làm", "309 Đường Số 8, P. 11", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("93529", "Ngói Đỏ BBQ", "918 Quang Trung, P. 8", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("233081", "Kem Dairy Queen - Lotte Mart Gò Vấp", "Tầng Trệt Lotte Mart Gò Vấp, 242 Nguyễn Văn Lượng, P. 10", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("666766", "Bún Đậu 426 - Cây Trâm", "395 Cây Trâm, P. 8", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("892524", "Don Chicken - Nhà Hàng Gà Nướng Hàn Quốc - Phan Văn Trị", "366A32 Phan Văn Trị, P. 5", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("72507", "Cơm Chay Việt - Nguyễn Thái Sơn", "103 Nguyễn Thái Sơn, P. 4", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("703989", "Không Gian Xanh - Ẩm Thực Hội An", "872/25/15 Quang Trung, P. 8", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("126552", "Cơm Tấm Cây Khế 3 - Cây Trâm", "126 Cây Trâm, P. 9", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("130239", "Vịt Lộn - Nguyễn Oanh", "Ngã 3 Nguyễn Oanh - Nguyễn Văn Lượng", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("879286", "Your Coffee Cart - Cafe Sữa Bọt", "254 Phạm Ngũ Lão, P. 7", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("743954", "Cô Thảo - Bánh Tráng Nướng", "405/47 Thống Nhất, P. 11", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("73333", "Ụt Ụt Coffee", "40 Nguyễn Tuân, P. 3", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("295471", "Bún Bò Ghẹ 7 Ghiền", "660 Lê Văn Thọ, P. 13", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("729798", "Sữa Chua Nếp Cẩm - Gà Cay Minh Hà - Shop Online", "200 Nguyễn Oanh, P. 17", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("72472", "Tiệm Bánh Mì Những Chàng Trai", "591 Thống Nhất, P. 16", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("217594", "Tiên Tiên - Bún Đậu Mắm Tôm & Nem Nướng", "206 Thống Nhất, P. 10", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("801641", "Cháo Lòng Bà Tư Mập", "14 Nguyễn Văn Dung, P. 6", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("250935", "Rất Quảng Quán - Mì Quảng", "35 Phạm Văn Đồng, P. 3", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("96301", "Style - Quán Nướng Ngói", "Chung Cư K26, P. 7", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("260306", "Nhà Hàng Đùi Cừu Nướng - Tân Sơn", "395/2 Tân Sơn", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("699733", "Friends By Pontian - Mì Singapore - Lotte Mart Gò Vấp", "Lotte Mart Gò Vấp, 242 Nguyễn Văn Lượng", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("1259", "Khúc Mùa Thu Cafe", "22/3 Đường Số 21, P. 8", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("273798", "Mặt Trời Đỏ - Buffet BBQ", "295 Phạm Văn Đồng, P. 1", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("107309", "Lẩu & Nướng Leng Keng", "66 Lê Lợi, P. 4", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("204747", "Kem Fanny - Emart Gò Vấp", "Tầng B2 - 3, Emart Gò Vấp, 366 Phan Văn Trị, P. 5", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("632537", "Cơm Niêu Thanh Dung - Vincom Quang Trung", "Tầng B1 Vincom Quang Trung, 190 Quang Trung, P. 10", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("710785", "Kenshin Tea - Trà Sữa Đồng Giá 19k - Quang Trung", "1096 Quang Trung", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("921963", "Hằng Ù - Chân Gà Rút Xương Ngâm Sả Tắc - Shop Online", "28/25 Lê Thị Hồng", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("243022", "Rest - Milk Tea & Coffee", "233 Phạm Văn Đồng, P. 1", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("84955", "Xì Trum Quán - Lê Thị Hồng", "40/72 Lê Thị Hồng, P. 17", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("720505", "Ding Tea - Quang Trung", "972 Quang Trung, P. 8", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("258232", "Đường Ray Quán - Lẩu & Nướng", "211 Phạm Văn Đồng, P. 1", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("241191", "Mì Cay & Cơm Chảo - Gia Hân Hân", "36 Đường 18, P. 8", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("313286", "Đất Sài Gòn - Cafe Ngắm Máy Bay", "389/24 Quang Trung, P. 10", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("752573", "Trà Sữa R&B Tea - 177 Quang Trung", "177 Quang Trung, P. 10", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("715855", "Mr.Good Tea - Cây Trâm", "433 Cây Trâm, P. 8 ", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("33317", "Quán Ăn Tâm Ký - Phan Huy Ích", "333 Phan Huy Ích, P. 12", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("12548", "Đào Nguyên - Cafe Sân Thượng", "101 Quang Trung", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("164913", "Món Ngon - Ăn Vặt - Shop Online", "108/794B Nguyễn Kiệm, P. 3", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("698695", "Ken's Coffee - Lê Lợi", "101 Lê Lợi, P. 4", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("145406", "Ăn Vặt Green Up - Phan Văn Trị", "558 Phan Văn Trị, P. 7", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("245970", "Bamboo Dimsum - Lotte Mart Gò Vấp", "Tầng Trệt Lotte Mart Gò Vấp, 242 Nguyễn Văn Lượng, P. 10", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("128384", "Cơm Tấm Tài - Nguyễn Văn Nghi", "100 Nguyễn Văn Nghi", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("105851", "Mực Rim Me Ngọc Phương - Đặc Sản Ba Miền", " 372 Nguyễn Oanh, P. 17", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("94302", "Trọng Tín - Xôi Gà", "104 Nguyễn Văn Nghi, P. 5 ", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("31650", "Mì Quảng Vinh", "111/23 Đường Số 8, P. 11", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("715701", "Ốc Lắc Cô Mai - Lê Thị Hồng", "36/114 Lê Thị Hồng, P. 17", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("707716", "Cơm Tấm Tròn", "18 Nguyễn Tuân, P. 3", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("2039", "Vuông Tròn Cafe", "24/2A Quang Trung", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("677494", "Hana Sushi - Nguyễn Văn Lượng", "282 Nguyễn Văn Lượng, P. 17", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("721439", "Meet & More - Trà Sữa Hàn Quốc - Lê Đức Thọ", "164 Lê Đức Thọ, P. 6", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("681213", "Quán Ngon - Bánh Hỏi Cháo Lòng & Bánh Canh Bột Gạo - Cây Trâm", "160 Cây Trâm, P. 9", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("106032", "Cháo Ếch Singapore - Quang Trung", "357 Quang Trung ", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("137120", "Funny - Trà Sữa & Bánh Tráng Trộn - Nguyễn Văn Công", "402 Nguyễn Văn Công, P. 3", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("127146", "Minh Khoa Café Phim ", "256/53 Phan Huy Ích, P. 12", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("673770", "Chả Lụi Lagi", "21 Nguyễn Văn Nghi, P. 4", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("779983", "BuoNo - Mì Ý Cay", "538/2 Quang Trung, P. 11", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("877709", "Mr. Sumo - Mì Ý - Shop Online", "448/30 Phan Huy Ích, P. 12", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("730602", "Uno Quán - Tea & Milktea - Phan Văn Trị", "733 Phan Văn Trị", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("776883", "Ten Ren's Tea - 485 Phan Văn Trị", "485 Phan Văn Trị, P. 5", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("6011", "Cõi Đá Cafe - Thống Nhất", "51/4A Thống Nhất, P. 11", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("728551", "Effoc Cafe - Phan Văn Trị", "661 Phan Văn Trị, P. 7", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("8201", "Data Sushi & Cafe", "4/72 Quang Trung  , P.10", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("1363", "Phở Quê Hương", "1223/4 Phan Văn Trị, P. 10", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("739921", "Vua Cà Ri - Nguyễn Oanh", "41/16 Nguyễn Oanh, P. 10", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("898045", "Kimbap Hoàng Tử - Món Hàn Quốc - Phan Văn Trị", "1069 Phan Văn Trị, P. 10", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("156893", "Kem Cuộn Thái Lan - 1124 Quang Trung", "1124 Quang Trung", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("880821", "K Quán 2 - Kem Chuối & Yaourt Bịch", "405/14 Nguyễn Oanh, P. 17", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("83550", "Tre Vàng - Quán Nhậu Sân Vườn", "538 Lê Văn Thọ, P. 13", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("163002", "Ẩm Thực Vợ Tôi - Hải Sản Nha Trang", "404 Thống Nhất, P. 16", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("733142", "Basax - Chicken & Korean Food - E Mart Gò Vấp", "366 Phan Văn Trị, P. 5", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("138535", "Nướng Tại Bàn 29K - Quang Trung", "Hẻm 872 Quang Trung", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("231391", "Bánh Mì Chảo 211", "211 Đường Số 3, P. 11", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("180574", "Bếp Của Mèo - Chả Hoa Online", "145/51/30 Lê Đức Thọ, P. 17", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("256266", "Xôi Bình Tiên - Nguyễn Văn Nghi", "254 Nguyễn Văn Nghi", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("70062", "Bánh Căn - Bánh Xèo Quán Tui", "1/30 Nguyễn Thái Sơn, P. 3", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("93036", "Bánh Canh Cua Tư Ù - Lê Quang Định", "672A Lê Quang Định, P. 1", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("683306", "Ẩm Thực Thành Huế - Cây Trâm", "287 Cây Trâm", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("662963", "Cuốn Việt - Coopmart Quang Trung", "Tầng Trệt Coopmart Quang Trung, 304A Quang Trung, P. 11", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("858264", "TonyTony Chopper - Lẩu & Mì Cay", "482 Nguyễn Thái Sơn, P. 5", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("741447", "Trà Đá Bơ 1102", "1 Phạm Văn Đồng", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("45296", "Tre Coffee", "468/2 Phan Văn Trị, P. 7 ", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("73069", "Bún Bò Bà Chiểu 2 - Lê Văn Thọ", "218A Lê Văn Thọ", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("633889", "Sài Gòn Nướng - Chung Cư K26", "372 Chung Cư K26 Dương Quảng Hàm", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("30813", "Đồng Xanh Cafe - Lê Đức Thọ", "1053 Lê Đức Thọ, P.13", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("663957", "King Beef BBQ", "16 Phạm Ngũ Lão, P. 4", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("155632", "Na Coffee - Nguyễn Văn Bảo", "15 Nguyễn Văn Bảo, P. 4", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("729080", "Joah Tea - Street Coffee", "198 Nguyễn Văn Nghi, P.7", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("174833", "Kem Tự Chọn Tank", "422 Quang Trung, P. 10", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("704155", "Triệu Vy - Bún Đậu Mắm Tôm", "17 Dương Quảng Hàm. P. 5", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("645490", "Cake Garden Coffee", "31/30 Lê Lai, P. 3", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("3454", "The Valentine - Tiệc Cưới", "18 Phan Văn Trị", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("246140", "Ốc 20k", "688/13 Quang Trung ", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("31540", "Phở Cô Lệ - Đường Số 1", "69 Đường Số 1, P.11", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("134198", "Cây Si Cafe - Lê Đức Thọ", "2 Lê Đức Thọ", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("651172", "Bún Bò Vương - Lê Thị Hồng", "42 Lê Thị Hồng, P. 17", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("72142", "Đắc Hùng - Vịt & Heo Quay - Nguyễn Oanh", "295 Nguyễn Oanh, P. 17", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("705928", "Mochi Mochi - Kem Tự Chọn - Lê Văn Thọ", "324 Lê Văn Thọ, P. 11", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("315708", "Phở Ngọc - Đường Số 3", "201 Đường Số 3, P. 9", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("207455", "Saigon NEW Restaurant - Phạm Văn Đồng", "327 - 329 Phạm Văn Đồng, P. 1", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("232011", "Vuvuzela Beer Club - Lotte Mart Gò Vấp", "18 Phan Văn Trị - Nguyễn Văn Lượng, P. 10", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("94294", "Ba Duy - Bánh Canh Cá Lóc", "243 Nguyễn Thái Sơn", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("240865", "S Phượt Coffee", "891/9 Nguyễn Kiệm, P. 3", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("194454", "Cây Si Cafe - Phạm Văn Đồng", "295 Phạm Văn Đồng", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("678684", "Chè - Súp Cua Quỳnh Như", "269 Đường Số 8, P. 11", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("147580", "Bánh Tráng Nướng - Lê Lợi", "30 Lê Lợi, P. 4", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("733209", "Cream DaLat - Kem Bơ - Phạm Văn Đồng", "330 Phạm Văn Đồng, P. 1", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("89784", "Bánh Trung Thu Rau Câu - Nguyễn Du", "22 Nguyễn Du, P. 7", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("116961", "Đồng Hương Quán", "199 Phạm Văn Đồng, P. 4", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("279030", "Quán Messi - Kem Tự Chọn", "1096 Quang Trung, P. 8", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("84292", "Chị Ngọc - Bánh Tráng Trộn Sài Gòn", "193 Đường số 28", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("47118", "Quán Chín Nghĩa - Dương Quảng Hàm", "173/45C Dương Quảng Hàm, P. 5", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("718552", "Trà Sữa Tea Expert - Phan Huy Ích", "303 Phan Huy Ích, P. 14", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("180118", "Kopapi & Juice", "95 Phạm Văn Đồng, P. 3", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("225669", "Thanh Vân - Bánh Ướt Ban Mê", "106 Phạm Văn Đồng, P. 3", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("14112", "Tường Phát - Hủ Tiếu Nam Vang - Quang Trung", "439 Quang Trung", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("195230", "Happy Cafecinema ", "1144/18 Lê Đức Thọ, P. 13", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("762015", "Sushi - Lunch Town - Shop Online", "294/40/16 Thống Nhất, P. 16", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("133148", "Nướng Ngói Sài Gòn Chi Nhánh 2 - Phạm Văn Đồng", "201 Phạm Văn Đồng, P.1", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("282092", "Mì Cay Singa", "699 Phan Văn Trị, P. 7", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("197899", "Nhà Hàng Thoáng Việt - Quang Trung", "1 Quang Trung", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("708583", "Kap Kap - Ẩm Thực Hoa & Cafe", "368 Phan Văn Trị, P. 5", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("182988", "Bánh Mì Xối Mỡ Mr. Beo", "327 Lê Văn Thọ", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("681149", "Trà Sữa Cú Mèo - Cây Trâm", "544 Cây Trâm", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("281550", "Delimanjoo - Bánh Bắp Kem Bơ", "945/4 Quang Trung, P. 14", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("729740", "Đạt Lý - Bánh Bột Lọc", "548/5 Nguyễn Thái Sơn, P. 5", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("216569", "Lẩu Công Chúa - Vincom Gò Vấp", "Tầng 4 Vincom Gò Vấp, 12 Phan Văn Trị", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("772531", "Lyn Tây - Kem, Sinh Tố & Cafe", "40 Phạm Văn Đồng, P. 3", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("92353", "Mì Vịt Tiềm Chí Phát - Nguyễn Văn Nghi", "402 Nguyễn Văn Nghi, P. 7", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("894224", "Bún Quậy Phú Quốc - Phan Văn Trị", "736 Phan Văn Trị, P. 10", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("66866", "Lẩu Dê Đoàn Râu", "95 Nguyễn Oanh, P. 17", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("723771", "Thế Giới Ăn Vặt - Thống Nhất", "362/21/23 Thống Nhất, P. 16", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("703858", "May Coffee House", "395 Phan Huy Ích, P. 14", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("31292", "Núi Ngự - Đặc Sản Ba Miền", "147/5 Đường số 23", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("124822", "Quán Ốc Trần Đào", "891/79 Nguyễn Kiệm", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("128665", "Nướng 274 - Phạm Văn Đồng", "274 Phạm Văn Đồng, P. 1", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("657221", "NP Quán - Các Món Ăn Vặt", "369 Lê Văn Thọ, P. 9", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("707845", "Quán Ăn 2H - Đặc Sản Nha Trang", "375 Lê Văn Thọ, P. 9", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("158966", "Bánh Xèo Cô Nguyệt", "774 Quang Trung, P. 8", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("724262", "Bánh Xèo Cô Dung", "40/56 Lê Thị Hồng, P. 17", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("1434", "Salado Cafe - Sân Vườn & Máy Lạnh", "58 Đường Số 5, Khu Cây Trâm, P. 9", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("713539", "Bột Chiên - Đường Số 7", "36 Đường Số 7, P. 3", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("32775", "Quán Ốc Út Nga", "9/13 Đường Số 11 , P. 11 ", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("744924", "Đốm - Milk Tea & Coffee", "672A47 Phan Văn Trị, P. 10", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("71848", "Xe Bánh Bèo Chén & Bánh Đập Vỉa Hè", "Góc Ngã 4 Lê Lợi & Lê Lai", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("30039", "Lẩu Bò 9 Ký", "117/2 Dương Quảng Hàm, P.5", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("187359", "Mì Cay Naga Viper 7 Cấp Độ", "140 Phạm Văn Đồng, P. 3", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("3111", "Biz Up Coffee Ice  Blended", "29 Nguyễn Văn Nghi, P. 4", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("50012", "Bánh Xèo Tài Tử - Gò Vấp", " Lý Thường Kiệt", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("139220", "Fins Coffee - Đường Số 10", "20 Đường Số 10, P. 9", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("225792", "Bánh Canh Thống Nhất", "17 Lê Lợi", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("138592", "Nhà Hàng Vườn Cau 2 - Nguyễn Thái Sơn", "171D Nguyễn Thái Sơn", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("42457", "Phở Trang - Nguyễn Oanh", "391 Nguyễn Oanh", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("900641", "Cơm Tấm Kuru", "305 Phạm Văn Đồng, P. 1", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("802969", "Bún Đậu Mẹt 128", "128 Phạm Văn Đồng, P. 3", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("277480", "Hoa Ly - Trà Sữa Nhà Làm - Phan Văn Trị", "637 Phan Văn Trị, P. 7", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("168242", "Trà Đào 168", "168 Lê Văn Thọ, P. 11", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("79642", "Cơm Gà Xối Mỡ SuSu", "440/65 Thống Nhất, P. 16", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("262620", "Kim Chi Fc - Chuyên Các Món Hàn Quốc", "157 Lê Đức Thọ, P. 17", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("85581", "Bánh Cóng Sóc Trăng", "8 Lý Thường Kiệt,  P. 8 ", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("24585", "Minh Hằng Bakery", "226 Nguyễn Thượng Hiền, P. 1", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("198787", "Hà Thúy Sài Gòn - Cơm Cháy Chà Bông Gia Truyền - Phan Văn Trị - Shop Online", "551/88 Phan Văn Trị, P. 5", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("157840", "Quán Đồng Quê 2A - Quang Trung", "16 Quang Trung, P. 11", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("141727", "YOLO Beer & Barbecue", "543/1 Phan Văn Trị, P. 7", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("102771", "Cơm Tấm Loan - Nguyễn Thái Sơn", "346 Nguyễn Thái Sơn", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("783069", "Xuân Đức - Lẩu Cua Đồng", "106 Đường Số 1, Khu Dân Cư Cityland Center Hills, P. 7", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("741810", "Alô Cú Đêm - Ăn Đêm Online", "590/2/10 Phan Văn Trị, P. 7", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("653237", "Bún Vịt Miến Gà - Ngon Nhất Quán", "1271 Phan Văn Trị, P. 10", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("746125", "TO's Tea & Food - Thiên Đường Trà Sữa Nhật - Lê Đức Thọ", "996 Lê Đức Thọ (Đối Diện Chợ Xóm Mới),, P. 13", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("646398", "3T - Trà Sữa", "Hẻm 904 Nguyễn Kiệm, P. 3", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("210782", "Bún Đậu Mắm Tôm Hà Nội - Thống Nhất", "51 Thống Nhất, P. 11", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("76914", "Delizia Coffee", "7 Phạm Ngũ Lão, P. 3", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("128659", "Ốc 10 Em", "50 Phạm Văn Đồng, P. 3", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("256201", "Ẩm Thực Chay Đỉnh Bồ Đề", "304 Nguyễn Thái Sơn, P. 4", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("233002", "Canh Bún & Bún Riêu Ốc", "656/18 Quang Trung, P. 11", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("776030", "K-Pop Chicken Restaurant", "37 Phạm Văn Đồng, P. 3", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("168452", "Oxy - Trà Sữa", "165 Đường Số 8, P. 11", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("244526", "Quán Ba Cư - Quán Ăn Gia Đình", "1 Chung Cư K26, Dương Quảng Hàm", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("785898", "Cơm Gà Xối Mỡ 365 - Đặc Biệt Các Loại Sốt", "365 Thống Nhất, P. 11", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("646949", "Mì Cay Singa", "1457 Phan Văn Trị, P. 10", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("227739", "Ngọc Thái - Các Loại Chè", "162 Nguyễn Văn Khối", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("1969", "Sao 2 Cafe - Lê Lợi", "79 Lê Lợi, P. 4", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("86994", "Quốc Anh Ký - Quán Cơm", "585 Lê Quang Định, P. 1", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("165243", "BUD'S Ice Cream - Vincom Quang Trung", "Tầng B1 Vincom Quang Trung, 190 Quang Trung, P. 10", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("198048", "Mahalo Beer Club - Quang Trung", "97 Quang Trung, P. 8", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("914781", "Avatar Coffee & Tea - Nguyễn Văn Nghi", "27 Nguyễn Văn Nghi, P. 4", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("728663", "Swiss Yogurt VietNam - Sữa Chua Uống Vị Trái Cây", "416/25 Dương Quảng Hàm, P. 5", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("77601", "Khu Ẩm Thực - Chợ Gò Vấp", "197 Nguyễn Thái Sơn, P. 4", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("78170", "New Town Cafe - Phạm Văn Đồng", "226 Phạm Văn Đồng", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("267985", "Bún Chả Hà Nội Xưa - Phạm Văn Bạch", "973 Phạm Văn Bạch, P. 12", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("29203", "Rio Cafe - Lê Đức Thọ", "57/29 Lê Đức Thọ, P. 17", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("313128", "Trà Sữa Blue Cup", "62 Lê Lai, P. 4", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("217749", "Quán Nướng Út Thảo ", "341 Phạm Văn Đồng, P. 11", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("783527", "The Little Bistro - Food & Drinks", "Tầng 1 - 2, 25 - 27 Trần Thị Nghỉ, P. 7", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("121840", "AEON Citimart Bakery", "672 Quang Trung", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("17893", "Garden Hills Coffee", "360 Dương Quảng Hàm, P. 5", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("152796", "Chè Mè Đen & Sữa Hạt Sen Cô Hoa - Huỳnh Khương An", "137 Huỳnh Khương An, P. 5", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("745775", "Trà Sữa Dế Cơm", "43 Thống Nhất", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("763967", "The AOH - Trà Sữa", "371 Nguyễn Kiệm, P. 3", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("146287", "Trà Sữa & Cafe H2t - Phan Văn Trị", "710/9 Phan Văn Trị, P. 10 ", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("79971", "Ốc Bà Chiểu 2", "Lý Thường Kiệt, P. 7", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("264916", "Ngọc Bảo - Lẩu Đuôi Bò", "1 Trưng Nữ Vương, P. 4", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("131113", "Quán Bo - Lê Đức Thọ", "23/19 Lê Đức Thọ, P. 13", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("216962", "Cô Anh - Bánh Xèo Miền Trung", "176 Cây Trâm", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("243110", "Trà Sữa The Moon", "185 Lê Văn Thọ, P. 8 ", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("692049", "Bún Đậu Mắm Tôm Phố Cổ", "1157 Phan Văn Trị", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("662197", "Văn Nghệ - Quán Bánh Khọt", "8 Lý Thường Kiệt", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("773534", "Món Ngon Xứ Quảng - Các Bà Dì", "6 Lê Đức Thọ, P. 7", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("710044", "Cachi Tea - Huỳnh Khương An", "66 Huỳnh Khương An, P. 5", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("147404", "Cháo Ếch Sư Phụ Singapore - Quang Trung", "143 Quang Trung, P. 10", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("82729", "Phở 10 Lý Quốc Sư - Lê Đức Thọ", "68 Lê Đức Thọ", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("630168", "Phở Hùng Ngân - Lê Đức Thọ", "2 Lê Đức Thọ", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("98919", "Ẩm Thực 45 - Quang Trung", "97 Quang Trung, P. 8", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("47681", "Bánh Cuốn Nóng Thuỳ Linh", "150 Nguyễn Văn Nghi", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("310140", "Lốc Coffee - Acoustic", "338 Nguyễn Văn Lượng, P. 16", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("53589", "Con Heo Cười - Da Heo Chiên Giòn - Giao Hàng Tận Nơi", "819/1 Nguyễn Kiệm, P. 3", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("243368", "Stir Crazy - Mongolian Grill/BBQ", "890 Quang Trung, P. 8", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("720957", "Bún Chả & Nem Cua Bể Hà Nội - Phan Văn Trị", "177 Thống Nhất, P. 11", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("98256", "Ốc Bầu ", "Hẻm 293 Lê Văn Thọ", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("763311", "Dumi Food & Cafe - Quang Trung", "777 Quang Trung, P. 12", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("710341", "Bánh Crepe Sầu Riêng - Gò Vấp", "Chung Cư Dream Home 2, Đường Số 59, P. 14", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("804177", "Cơm Gà Hồng Kông - Phạm Ngũ Lão", "182 Phạm Ngũ Lão, P. 7", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("702786", "Phở Bò Tơ Củ Chi A. Dũng", "89 Nguyễn Thái Sơn", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("749516", "Cá Biển Nha Trang 2", "Đối Diện 372 Dương Quảng Hàm, Chung Cư K26 Dương Quảng Hàm, P. 7", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("208029", "Lotus Coffee", "498/1/3 Lê Quang Định, Phường 1", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("225171", "Canteen - Cafe & Giải Khát - Phạm Ngũ Lão", "5B Phạm Ngũ Lão, P. 3", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("654010", "Gỗ Mục Coffee", "102/18 Lê Văn Thọ, P. 11", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("104767", "Lẩu 38 - Đường Số 11", "38 Đường Số 11, P. 11", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("774945", "Trà Sữa Wozzi", "41 Nguyễn Văn Nghi, P. 4", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("300651", "My Coffee", "Hẻm 452 Phan Văn Trị", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("742610", "A Đạt - Bánh Xèo Rau Rừng - Không Chi Nhánh", "1 Phạm Văn Đồng", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("232070", "Nem Nướng Thanh Hùng", "151 Đường Số 11, P. 11", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("215011", "Tàu Hũ Orisoy - Vincom Plaza Gò Vấp", "Tầng 4 - Vincom Plaza Gò Vấp, 12 Phan Văn Trị, P. 7", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("49623", "Sweet Home Bakery - Quang Trung", "294 Quang Trung. P. 10", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("281591", "Vitamin House - Quang Trung", "330 Quang Trung, P. 10", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("126815", "My Life - Quán Bò Né", "736 Phạm Văn Bạch ,P. 12", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("9164", "Quán Sáu Cua - Hải Sản Tươi Sống", "125/4 Đường Số 11 , P. 11", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("635599", "Rice Club Gò Vấp", "Tầng Trệt Siêu Thị AeonCitimart Quang Trung, 672 Quang Trung, P. 11", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("286061", "Bánh Bèo Hai Quân - Lê Văn Thọ", "417/53 Lê Văn Thọ, P. 9", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("789285", "Chú Nhiều 444 - Hủ Tiếu Mì & Sủi Cảo", "891/91 Nguyễn Kiệm, P. 3", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("3685", "Gốc Cây Cafe", "94/1055 Dương Quảng Hàm, P. 6", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("137182", "Quán Ăn Gia Đình Bạn Tôi - Nguyễn Thượng Hiền", "36 Nguyễn Thượng Hiền, P. 1", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("317333", "Quán Bo - Bún Mắm & Bánh Canh Cua", "1196 Lê Đức Thọ", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("208114", "Quán Lâm Ký - Bột Chiên", "652 Lê Quang Định, P. 1", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("788582", "Đá Bào Kidi", "70 Nguyễn Tư Giản, P. 12", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("862793", "Ding Tea - Vincom Plaza Gò Vấp", "Tầng 4 Vincom Plaza Gò Vấp, 12 Phan Văn Trị, P. 7", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("736240", "Cô Ba Sài Gòn - Bún Thịt Nướng & Cơm Thịt Xiên - Lê Lai", "79 Lê Lai, P. 3", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("874849", "Quán Của Má - Nem Nướng & Đặc Sản Nha Trang - Trần Thị Nghỉ", "144 Trần Thị Nghỉ, P. 7", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("184670", "Trái Cây Tô Sốt Dừa Fruta", "Đối Diện Số 93 Bùi Quang Là", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("228077", "Lê Uyên - Trà Sữa Thạch Nhà Làm", "497 Thống Nhất, P. 16", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("710782", "Quán Lươn Củ Nghệ", "440/44A Thống Nhất, P. 16", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("782040", "Al Fresco's - Phan Văn Trị", "539 Phan Văn Trị, P. 5", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("786049", "Bò Tơ Nhân Phát - Lê Quang Định", "516 Lê Quang Định, P. 1", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("670900", "Quán Đức Đà Nẵng - Mì Quảng & Bún Bò", "220/9 Cây Trâm, P. 9", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("31262", "Phúc Tam Kỳ - Mì Quảng", "297 Nguyễn Văn Lượng , P. 10", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("136393", "Cây Xoài - Bún Thịt Nướng & Cơm Tấm", "1238 - 1240 Quang Trung, P. 8", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("782099", "Puppy - Trà Sữa & Coffee", "716 Lê Đức Thọ, P. 15", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("287418", "Cát Coffee", "Tầng 3, 228/4 Phan Huy Ích , P. 12", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("748777", "Trâm Anh - Bún Riêu Bạch Tuộc", "862/13 Lê Đức Thọ, P. 15", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("93522", "Bánh Canh Chả Cá Vũng Tàu", "499/6/15 Quang Trung, P. 10", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("204162", "Trà Sữa Green Life", "Đường Số 21", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("91811", "Phương Thu - Bún Chả Hà Nội", "152 Nguyễn Oanh, P. 17", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("642375", "Feel Coffee & Tea Express - Nguyễn Văn Bảo", "1 Nguyễn Văn Bảo", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("755920", "Hệ Thống Hàu 5K Sài Gòn - Lê Đức Thọ", "265 Lê Đức Thọ, P. 17", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("105242", "Bánh Tráng Trộn - Cây Trâm", "Hẻm 21, đường Cây Trâm, P. 8", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("190128", "Kem Dừa", "Nguyễn Văn Bảo", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("201269", "Cơm Tấm 144", "144 Phạm Ngũ Lão", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("29785", "Suối Ngàn Cafe - Nguyễn Huy Điển", "2 Bis Nguyễn Huy Điển, P. 7", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("191804", "Lado Coffee", "Khu Tập Thể Biên Phòng, 683/1 Nguyễn Kiệm, P. 3", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("195597", "Quán Lâm Bô - Xiên Que & Lẩu Nhúng", "1 Quang Trung", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("193595", "Đông Hà - Bánh Canh Cá Lóc - Nguyên Hồng", "27Bis Nguyên Hồng, P. 1", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("259345", "Xiên Nướng Phố Vui", "102/44 Lê Văn Thọ, P. 25", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("79534", "Lúa Cafe", "179 Thống Nhất, P. 11  ", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("868050", "Kyoto SaBo - Quán Ăn Nhật Bản", "138/40/11 Nguyễn Duy Cung, P. 12", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("698663", "Bún Đậu Tre - Quang Trung", "775 Quang Trung, P. 12", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("736009", "Hok Tea - Trà Sữa Đài Loan - Bạch Đằng", "223 - 225 Bạch Đằng, P. 3", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("720463", "Ăn Vặt Na Shop - Chân Gà Sả Tắc - Shop Online", "169 Huỳnh Văn Nghệ, P. 12", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("248982", "T.A Trà Sữa & Boardgame", "226/2 Nguyễn Thái Sơn, P. 4", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("126434", "Nướng Ngói 133", "133 Đường Số 11, P. 11", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("703133", "Lẩu Dê Bình Dương - Đường Số 27", "44A Đường Số 27", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("739551", "Nước Mía Xanh Lá", "109 Đường Số 8, P. 11", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("119303", "Bánh Phô Mai Ông Già", "133/36/60 Quang Trung, P. 10", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("1262", "Dạ Khúc Cafe", "32/100 Đường 59, P. 14", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("750651", "Royal Tea Viet Nam By HongKong - 5 Quang Trung", "5 Quang Trung", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("670159", "Bún Đậu Mẹt Mắm Tôm", "282 Thống Nhất, P. 16", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("178062", "Dê Tươi Mái Lá", "1 Huỳnh Văn Nghệ, P. 12", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("294284", "Menu24h.vn - Tổ Chức Tiệc Lưu Động ", "334/5 Nguyễn Văn Nghi", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("711697", "Chả Lụa Bò 39 - Shop Online", "709 Phan Văn Trị, P. 7", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("251690", "TYKEO - The Drink And Workshop", "497/8/17 Phan Văn Trị, P. 5", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("719514", "Ẩm Thực Chay Thiện Trí", "Nhà Công Vụ Số 2, Phạm Ngũ Lão, P. 3", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("699610", "Cỏ Coffee", "1189 Phan Văn Trị, P. 10", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("33341", "Cơm Tấm Tứ Hải", "300 Phan Huy Ích, P. 12", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("702779", "Hủ Tiếu Nam Vang Ngọc Nhung", "534 Nguyễn Thái Sơn", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("281921", "1987 - Quán Trà Sữa", "214/9 Nguyễn Oanh, P. 17", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("688348", "A Ke - Mì Xào Giòn", "Nguyễn Thái Sơn, P. 4", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("748978", "Venus Coffee & Tea", "80/113 Dương Quảng Hàm, P. 5", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("703484", "Bánh Canh Cua 36 - Lê Lai", "36 Lê Lai", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("227741", "Quán Chay An Khang", "179 Cây Trâm", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("88033", "Bánh Xèo Miền Trung - Nguyễn Văn Lượng", "Nguyễn Văn Lượng", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("190917", "Hoa Ban Quán - Đặc Sản Heo Tộc", "245/31 Đường Số 20 (Dương Quảng Hàm),, P. 5", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("723083", "Little Saigon - Bún Đậu Mẹt", "376 Lê Văn Thọ, P. 11", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("131706", "Phở Chú Phương - Đường Số 18", "16/6 Đường Số 18, P. 8", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("300928", "Gocsi Cafe", "Hẻm 89 Đường Số 59, P. 14", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("715881", "Trà Sữa Milky Homemade", "319/20 Lê Văn Thọ, P. 9", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("25262", "XP Garden Cafe - Cafe Sân Vườn", "94/1048 Dương Quảng Hàm, P. 6", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("279774", "Bún Chả Cá Minh Sơn - Đường Số 12", "34D Đường Số 12, P. 11", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("90195", "Quán Sen - Nhậu Bình Dân", "310/29A Đường15, Dương Quảng Hàm, P. 5", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("628365", "Trà Sữa Nhà Làm - Quang Trung", "656/65/4 Quang Trung, P. 11", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("693524", "Suri Quán - Đùi Gà Bó Xôi", "656/65/2 Quang Trung, P. 11", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("4181", "My Way Cafe - Phan Văn Trị", "18 Phan Văn Trị, Phường 10", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("142623", "Trâm Anh - Lẩu Nấm Giao Hàng Tận Nơi", "129/7 Đường Số 3, P. 11", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("227734", "Fins Coffee - Cây Trâm", "8 Cây Trâm, P. 9", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("31654", "Quán Xuân - Cháo Gỏi Vịt", "35 -37 Lê Văn Thọ , P.8", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("753796", "Bún Đậu Ngon Cây Trâm", "298 Cây Trâm, P. 9", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("222099", "Phở Vị Hoàng", "2 - 4 Lê Lai, P. 3", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("143560", "HUP Acoustic Cafe - Nguyễn Văn Lượng", "312 Nguyễn Văn Lượng, P. 16", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("215514", "Su Que 79", "120 Lê Văn Thọ, P. 11", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("670141", "Siucha - Trà Sữa", "204 Lê Văn Thọ, P. 11", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("119061", "Hủ Tiếu Miền Tây - Nguyễn Văn Bảo", "Hẻm 59 Nguyễn Văn Bảo, P. 4", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("290784", "Dasis Tea & Coffee House - Emart Gò Vấp", "Emart Gò Vấp, 366 Phan Văn Trị, P. 5", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("108409", "Phở Lộc - Quang Trung", "96 Quang Trung, P. 10", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("97126", "Cò Kếu Bờ Sông - Quán Ăn Ven Sông", "147B Đường Số 23 , P. 5", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("789629", "The Menu Restaurant - Pizza & Pasta", "188 Phan Huy Ích, P. 12", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("209034", "Trà Sữa Happy Life - Phan Huy Ích", "18 - 19 Phan Huy Ích, P. 12", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("222894", "Simple Coffee - Acoustic Live", "498 Cây Trâm, P. 9", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("122262", "Coconut Coffee ", "730/46 Lê Đức Thọ, P. 15", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("731325", "Bánh Mì Xíu Mại Gốc Đà Lạt", " 76 Đường Số 1, P. 16", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("703109", "Hồng Ngọc - Bún Chả Hà Nội & Bún Đậu Mắm Tôm", "210 Lê Đức Thọ, P. 6", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("131446", "Chè Bưởi Vĩnh Long - Thống Nhất", "399 Thống Nhất, P. 11", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("741043", "Bánh Tráng Trộn & Cuốn - Lê Đức Thọ", "57/38 Lê Đức Thọ, P. 7", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("291837", "Gấu Crepe & Milk Tea", "108 Đường Số 1, P. 16", "Quận Gò Vấp", "TP. HCM", "2"),
                Restaurant("778009", "The Check In - Sữa Đậu Nành & Sữa Chua Lắc", "381 Lê Văn Thọ, P. 9", "Quận Gò Vấp", "TP. HCM", "2"),

                )


    }

}
